#!/bin/bash
#SBATCH -n 1
#SBATCH -c 4
#SBATCH --mem=10G
#SBATCH -p qTRD
#SBATCH --time=20:00:00
#SBATCH -J fnc
#SBATCH -e /data/users2/jwardell1/nshor_docker/examples/devcog-project/jobs/error%A_%a.err
#SBATCH -o /data/users2/jwardell1/nshor_docker/examples/devcog-project/jobs/out%A_%a.out
#SBATCH -A psy53c17
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jwardell1@student.gsu.edu
#SBATCH --oversubscribe

sleep 5s

#SLURM_ARRAY_TASK_ID=0

SUB_PATHS_FILE=/data/users2/jwardell1/nshor_docker/examples/devcog-project/helper_scripts/paths_fnc

IFS=$'\n'
paths_array=($(cat ${SUB_PATHS_FILE}))
sub_ix=$(( 3*$SLURM_ARRAY_TASK_ID ))
tc_ix=$(( 3*$SLURM_ARRAY_TASK_ID + 1 ))
out_ix=$(( 3*$SLURM_ARRAY_TASK_ID + 2 ))

sub_id=${paths_array[${sub_ix}]}
tc_file=${paths_array[${tc_ix}]}
out_dir=${paths_array[${out_ix}]}


export PATH=/data/users2/jwardell1/miniconda3/bin:$PATH

source /data/users2/jwardell1/miniconda3/etc/profile.d/conda.sh

conda activate /data/users2/jwardell1/miniconda3/envs/ica-torch

downsampling_factor=1

python /data/users2/jwardell1/nshor_docker/examples/devcog-project/helper_scripts/compute_fnc.py $sub_id $tc_file $out_dir $downsampling_factor

wait

sleep 10s
