#!/bin/bash
#SBATCH -n 1
#SBATCH -c 4
#SBATCH --mem=5g
#SBATCH -p qTRD
#SBATCH -t 2-00:00
##SBATCH --array=0-368
#SBATCH -J fbirn-test
#SBATCH -e /data/users2/jwardell1/nshor_docker/fbirn-project/jobs/error%A.err
#SBATCH -o /data/users2/jwardell1/nshor_docker/fbirn-project/jobs/out%A.out
#SBATCH -A psy53c17
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jwardell1@student.gsu.edu
#SBATCH --oversubscribe

sleep 5s

module load singularity/3.10.2

DATA_LOCATION=/data/qneuromark/Data/FBIRN/Data_BIDS/Raw_Data/
DATA_BIND_POINT=/data
SIF_FILE=/data/users2/washbee/tdassist/Dockerbuild/nshor2.sif
RUN_BIND_POINT=/run/
SCRIPT_NAME=pd_dockerParralelized_fbirn.sh
OUTPUT_DIRECTORY=/data/users2/jwardell1/nshor_docker/fbirn-project/
OUTPUT_BINDING=/out
SUBJECTS_FILE=/data/users2/jwardell1/nshor_docker/fbirn-project/subjects.txt

singularity exec --bind .:${RUN_BIND_POINT},${DATA_LOCATION}:${DATA_BIND_POINT},${OUTPUT_DIRECTORY}:${OUTPUT_BINDING} ${SIF_FILE} ${RUN_BIND_POINT}${SCRIPT_NAME} ${SLURM_ARRAY_TASK_ID} ${SUBJECTS_FILE} &

wait

sleep 10s
