#!/bin/bash
#SBATCH -n 1
#SBATCH -c 4
#SBATCH --mem=256G
#SBATCH -p qTRDHM
#SBATCH --time=20:00:00
#SBATCH -J OTCD
#SBATCH -e /data/users2/jwardell1/nshor_docker/examples/hcp-project/jobs/error%A.err
#SBATCH -o /data/users2/jwardell1/nshor_docker/examples/hcp-project/jobs/out%A.out
#SBATCH -A psy53c17
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jwardell1@student.gsu.edu
#SBATCH --oversubscribe

sleep 5s


export PATH=/data/users2/jwardell1/miniconda3/bin:$PATH

source /data/users2/jwardell1/miniconda3/etc/profile.d/conda.sh

conda activate /data/users2/jwardell1/miniconda3/envs/ica-torch


python /data/users2/jwardell1/nshor_docker/examples/hcp-project/helper_scripts/organize_tc_data.py


wait

sleep 10s
