#!/bin/bash
#SBATCH -n 1
#SBATCH -c 4
#SBATCH --mem=20G
#SBATCH -p qTRD
#SBATCH --time=00:15:00
#SBATCH -J SLAfbirn
#SBATCH -e /data/users2/jwardell1/nshor_docker/examples/fbirn-project/FBIRN/subject_level_analysis/jobs/error%A_%a.err
#SBATCH -o /data/users2/jwardell1/nshor_docker/examples/fbirn-project/FBIRN/subject_level_analysis/jobs/out%A_%a.out
#SBATCH -A psy53c17
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jwardell1@student.gsu.edu
#SBATCH --oversubscribe

sleep 5s


export PATH=/data/users2/jwardell1/miniconda3/bin:$PATH

source /data/users2/jwardell1/miniconda3/etc/profile.d/conda.sh

conda activate /data/users2/jwardell1/miniconda3/envs/ica-torch


PATHS_FILE=/data/users2/jwardell1/nshor_docker/examples/fbirn-project/FBIRN/subject_level_analysis/paths

GICA_DIR=/data/users2/jwardell1/ica-torch-gica/standalone_gica_script

IFS=$'\n'
paths_array=($(cat ${PATHS_FILE}))
sub_ix=$(( 4*$SLURM_ARRAY_TASK_ID ))
func_ix=$(( 4*$SLURM_ARRAY_TASK_ID + 1 ))
out_ix=$(( 4*$SLURM_ARRAY_TASK_ID + 2 ))
mask_ix=$(( 4*$SLURM_ARRAY_TASK_ID + 3 ))

subject_ID=${paths_array[${sub_ix}]}
func_filepath=${paths_array[${func_ix}]}
output_path=${paths_array[${out_ix}]}
mask_filepath=${paths_array[${out_ix}]}

python ${GICA_DIR}/subject_level_pca.py $subject_ID $func_filepath $output_path $mask_filepath


wait

sleep 10s
